export declare const is: (val: unknown, type: string) => boolean;
export declare const isDef: (val: any) => boolean;
export declare const isUnDef: (val: any) => boolean;
export declare const isNull: (val: any) => boolean;
export declare const isNullOrUnDef: (val: any) => boolean;
export declare const isObject: (val: any) => boolean;
export declare const isString: (val: any) => boolean;
export declare function isNumber(val: any): boolean;
export declare const isArray: (val: any) => any;
export declare const isEmpty: (val: any) => boolean;
export declare const isFunction: (val: any) => boolean;
